# This is a basic workflow to help you get started with Actions

name: CI


on:
  pull_request:
    paths:
      - 'operations/us-east-1/containers/wazuh-reports/daily/**'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Log level'
        required: true
        default: $GITHUB_SHA
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $GITHUB_SHA"
        env:
          GITHUB_SHA: ${{ inputs.image_tag }}
